#include "icones/diadia.h"
#include "icones/play.h"
#include "icones/lavagens.h"
#include "icones/fast.h"
#include "icones/sol.h"
#include "icones/pesada.h"
#include "icones/fundo.h"
#include "icones/voltar.h"
#include "icones/home.h"
#include "icones/menu.h"
#include "icones/animabub/bubleanima1.h"
#include "icones/animabub/bubleanima2.h"
#include "icones/animabub/bubleanima3.h"
#include "icones/animabub/bubleanima4.h"
#include "icones/animabub/bubleanima5.h"
#include "icones/animabub/bubleanima6.h"
#include "icones/animabub/bubleanima7.h"
#include "icones/animabub/bubleanima8.h"
#include "icones/animabub/bubleanima9.h"
#include "icones/animabub/bubleanima10.h"
#include "icones/animabub/bubleanima11.h"
#include "icones/animabub/bubleanima12.h"
#include "icones/animabub/bubleanima13.h"
#include "icones/animabub/bubleanima14.h"

//Todas as imagens foram retiradas do site https://icons8.com/  - FREE DESIGN RESOURCES AND SOFTWARE
